#Implemented datasets
import os

ROOT_DIR = os.environ['DATA_ROOT'] if 'DATA_ROOT' in os.environ else '.'

ML1M = 'ml1m'
LFM1M = 'lfm1m'
CELL = 'cellphones'
COCO = 'coco'

USER = 'user'
PRODUCT = 'product'
ENTITY = 'entity'
RELATION = 'relation'
INTERACTION = {
    ML1M: "watched",
    LFM1M: "listened",
    CELL: "purchase",
    COCO: "interacted"
}
SELF_LOOP = 'self_loop'
PRODUCED_BY_PRODUCER = 'produced_by_producer'
PRODUCER = 'producer'

# ML1M ENTITIES
CINEMATOGRAPHER = 'cinematographer'
PRODCOMPANY = 'prodcompany'
COMPOSER = 'composer'
CATEGORY = 'category'
ACTOR = 'actor'
COUNTRY = 'country'
WIKIPAGE = 'wikipage'
EDITOR = 'editor'
WRITTER = 'writter'
DIRECTOR = 'director'

# LASTFM ENTITIES
ARTIST = 'artist'
ENGINEER = 'engineer'
GENRE = 'genre'

# CELL ENTITIES
BRAND = 'brand'
RPRODUCT = 'rproduct'

# COCO ENTITIES
LEVEL = 'level'
LANGUAGE = 'language'
CONCEPT = 'concept'
AUDIENCE = 'audience'

# ML1M RELATIONS
DIRECTED_BY_DIRECTOR = 'directed_by_director'
PRODUCED_BY_COMPANY = 'produced_by_prodcompany'
STARRED_BY_ACTOR = 'starred_by_actor'
RELATED_TO_WIKIPAGE = 'related_to_wikipage'
EDITED_BY_EDITOR = 'edited_by_editor'
WROTE_BY_WRITTER = 'wrote_by_writter'
CINEMATOGRAPHY_BY_CINEMATOGRAPHER = 'cinematography_by_cinematographer'
COMPOSED_BY_COMPOSER = 'composed_by_composer'
PRODUCED_IN_COUNTRY = 'produced_in_country'
BELONG_TO_CATEGORY = 'belong_to_category'

# LASTFM RELATIONS
MIXED_BY_ENGINEER = 'mixed_by_engineer'
FEATURED_BY_ARTIST = 'featured_by_artist'
BELONG_TO_GENRE = 'belong_to_genre'

# CELL RELATIONS
PURCHASE = 'purchase'
ALSO_BOUGHT_RP = 'also_bought_related_product'
ALSO_VIEWED_RP = 'also_viewed_related_product'
ALSO_BOUGHT_P = 'also_bought_product'
ALSO_VIEWED_P = 'also_viewed_product'

# COCO RELATIONS
RELATED_TO_CONCEPT = 'related_to_concept'
TAUGHT_IN_LEVEL = 'taught_in_level'
TAUGHT_IN_LANGUAGE = 'taught_in_language'
HAS_TARGET_AUDIENCE = 'has_target_audience'

ENTITY_LIST = {
    ML1M: [USER, PRODUCT, ACTOR, DIRECTOR, PRODCOMPANY, EDITOR, WRITTER, CINEMATOGRAPHER, COMPOSER, COUNTRY,
           CATEGORY, PRODUCER, WIKIPAGE],
    LFM1M: [USER, PRODUCT, ARTIST, ENGINEER, GENRE, PRODUCER],
    CELL: [PRODUCT, BRAND, GENRE, RPRODUCT, USER],
    COCO: [USER, PRODUCT, LEVEL, LANGUAGE, CONCEPT, AUDIENCE, CATEGORY]
}


RELATION_LIST = {
    ML1M: [INTERACTION[ML1M], BELONG_TO_CATEGORY, PRODUCED_BY_PRODUCER, DIRECTED_BY_DIRECTOR,
           PRODUCED_BY_COMPANY, STARRED_BY_ACTOR, EDITED_BY_EDITOR, WROTE_BY_WRITTER,
           CINEMATOGRAPHY_BY_CINEMATOGRAPHER, COMPOSED_BY_COMPOSER, PRODUCED_IN_COUNTRY,
           RELATED_TO_WIKIPAGE],
    LFM1M: [INTERACTION[LFM1M], BELONG_TO_GENRE, FEATURED_BY_ARTIST, MIXED_BY_ENGINEER, PRODUCED_BY_PRODUCER],
    #CELL: [INTERACTION[CELL], BELONG_TO_CATEGORY, PRODUCED_BY_COMPANY, ALSO_VIEWED_P, ALSO_BOUGHT_P, ALSO_BOUGHT_RP, ALSO_VIEWED_RP]
    COCO: [INTERACTION[COCO], RELATED_TO_CONCEPT, TAUGHT_IN_LEVEL, TAUGHT_IN_LANGUAGE, HAS_TARGET_AUDIENCE, BELONG_TO_CATEGORY]
}



# REVERSED RELATIONS
REV_PREFIX = 'rev_'
REV_PRODUCED_BY_PRODUCER = REV_PREFIX + PRODUCED_BY_PRODUCER
REV_INTERACTION = {
    ML1M: REV_PREFIX + "watched",
    LFM1M: REV_PREFIX + "listened",
    CELL: REV_PREFIX + "purchase",
}
# REVERSED RELATIONS ML1M
REV_DIRECTED_BY_DIRECTOR = REV_PREFIX + DIRECTED_BY_DIRECTOR
REV_PRODUCED_BY_COMPANY = REV_PREFIX + PRODUCED_BY_COMPANY
REV_STARRED_BY_ACTOR = REV_PREFIX + STARRED_BY_ACTOR
REV_RELATED_TO_WIKIPAGE = REV_PREFIX + RELATED_TO_WIKIPAGE
REV_EDITED_BY_EDITOR = REV_PREFIX + EDITED_BY_EDITOR
REV_WROTE_BY_WRITTER = REV_PREFIX + WROTE_BY_WRITTER
REV_CINEMATOGRAPHY_BY_CINEMATOGRAPHER = REV_PREFIX + CINEMATOGRAPHY_BY_CINEMATOGRAPHER
REV_COMPOSED_BY_COMPOSER = REV_PREFIX + COMPOSED_BY_COMPOSER
REV_PRODUCED_IN_COUNTRY = REV_PREFIX + PRODUCED_IN_COUNTRY
REV_BELONG_TO_CATEGORY = REV_PREFIX + BELONG_TO_CATEGORY

#REVERSED RELATIONS LFM1M
REV_MIXED_BY_ENGINEER = REV_PREFIX + MIXED_BY_ENGINEER
REV_FEATURED_BY_ARTIST = REV_PREFIX + FEATURED_BY_ARTIST
REV_BELONG_TO_GENRE = REV_PREFIX + BELONG_TO_GENRE

#REVERSED COCO RELATIONS
REV_RELATED_TO_CONCEPT = REV_PREFIX + RELATED_TO_CONCEPT
REV_TAUGHT_IN_LEVEL = REV_PREFIX + TAUGHT_IN_LEVEL
REV_TAUGHT_IN_LANGUAGE = REV_PREFIX + TAUGHT_IN_LANGUAGE
REV_HAS_TARGET_AUDIENCE = REV_PREFIX + HAS_TARGET_AUDIENCE